spring:
  application:
    name: medilabo-gateway
  cloud:
    config:
      import-check:
        enabled: false
server:
  port: 9005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


