spring:
  application:
    name: medilabo-gateway
  cloud:
    config:
      import-check:
        enabled: false
server:
  port: ${PORT:9005}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/


