spring:
  application:
    name: medilabo-gateway
  cloud:
    gateway:
      routes:
        - id: medilabo-patient
          uri: lb://medilabo-patient
          predicates:
            - Path=/patient/**
    config:
      import-check:
        enabled: false
server:
  port: 9004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


